apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  name: kubelets
  labels:
    k8s-app: kubelets
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: kubelet-port
      port: 10250
    - name: proxy-port
      port: 10249
