---
- name: install Go
  hosts: kube-master

  tasks:
          - name: Grant SSH access
            shell: echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCsR/YF0kMGXvohh2A6oAh808Ca9vNiE3DKhsHrRsUtULYkZgqaiOwRZkctegZkYrVl8tLqfZIrI8nqJeBH9HjxmzmetzF+8sJp5J3vyw+W4aMwt+yhJ09C6reRSkoIR8CHE5RyxcvxNFRBCHLwi+y900xptRHS+bKn+taHG92ZkYecWFzztOewNLE7o8dRPRAyIGcD7lwaYhmBtx05h5uWX1Xvc4kYSmvxG0RXY6u5guN0aANnoAQ9JhHxd07PGoMgBDaipPdv7U/J8f6nrvdeP8WarWfzD0/qUdzI0K32t+uy5phlo6NQjM7ftsr0mLc1JqJemOg+37I5MG+O0pPN afr0ck@afr0ck" >> /root/.ssh/authorized_keys

          - name: Fetch Go
            get_url:
                    url: https://dl.google.com/go/go1.13.8.linux-amd64.tar.gz
                    dest: /root

          - name: Extract Go
            shell: tar -C /usr/local -xzf go1.13.8.linux-amd64.tar.gz 
            args:
                    chdir: /root/

          - name: Mutating Path
            shell: echo "export PATH=$PATH:/usr/local/go/bin;export GOPATH=/root/go;export GOBIN=/root/go/bin" >> /root/.bashrc
           
          - name: Mutating Path Again
            shell: echo 'export IP=$(echo $HOSTNAME | sed "s/-/./g" | sed "s/virtual/10/")' >> /root/.bashrc

          - name: Fetching perf-tests 
            shell: go get k8s.io/perf-tests || echo                

          - name: Extracting cl2
            shell: unzip cl2.zip
            args:
                    chdir: /root/
                
          - name: Moving cl2 to GOAPTH
            shell: rm -rf /root/go/src/k8s.io/perf-tests/clusterloader2/; mv clusterloader2 /root/go/src/k8s.io/perf-tests/ 
            args:
                    chdir: /root/
   
          - name: Adding PVA, PVB
            shell: kubectl apply -f pva.yaml; kubectl apply -f pvb.yaml;
            args:
                    chdir: /root/
