apiVersion: apps/v1
kind: Deployment
metadata:
    name: "defactod"
spec:
    replicas: 1
    selector:
        matchLabels:
            app: test
    template:
        metadata:
            labels:
                app: test
        spec:
            containers:
                - name: pause
                  image: gcr.io/google-containers/pause
